name: Java CI with mvn

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2-
      - name: Build with Maven
        run: mvn -B clean verify
      - name: Deploy to Maven Repository
        run: mvn -B deploy
        env:
          MAVEN_USERNAME: ${{ secrets.MAVEN_SERVER_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_SERVER_PASSWORD }}
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: maven-artifacts
          path: target/*.jar